caixia:
  config:
    name: caixia
    birthday: 19911029

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caixia?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

## Freemarker 配置
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点

  rabbitmq:
    host: 192.168.0.145
    port: 31293
    username: admin
    password: long2018
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true #消息发送到交换机确认机制，是否返回回调
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        retry:
           enabled: true # 是否支持重试

  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0

  data:
    mongodb:
      uri: mongodb://localhost
      host: localhost
      port: 27017
      database: caixia


## Mybatis 配置
mybatis:
  type-aliases-package: com.caixia.entity
  mapper-locations: classpath:mapper/*.xml

